function(compile_shader SHADER)
    set(SHADER_ASSET_PATH ${SHADER_ASSETS_DIR}/${SHADER})
    set(SHADER_OUTPUT_PATH ${SHADER_OUTPUT_DIR}/${SHADER}.spv)
    find_program(GLSLC glslc)
    get_filename_component(SHADER_OUTPUT_DIRECTORY ${SHADER_OUTPUT_PATH} DIRECTORY)
    file(MAKE_DIRECTORY ${SHADER_OUTPUT_DIRECTORY})
    exec_program(${GLSLC} ARGS -o ${SHADER_OUTPUT_PATH} ${SHADER_ASSET_PATH})
endfunction()

compile_shader(simple_shader.vert)
compile_shader(simple_shader.frag)