function(compile_shader SHADER)
    set(SHADER_ASSET_PATH ${SHADER_ASSETS_DIR}/${SHADER})
    set(SHADER_OUTPUT_PATH ${SHADER_OUTPUT_DIR}/${SHADER}.spv)
    find_program(GLSLC glslc)
    get_filename_component(SHADER_OUTPUT_DIRECTORY ${SHADER_OUTPUT_PATH} DIRECTORY)
    file(MAKE_DIRECTORY ${SHADER_OUTPUT_DIRECTORY})
    exec_program(${GLSLC} ARGS -o ${SHADER_OUTPUT_PATH} ${SHADER_ASSET_PATH})
endfunction()

function(compile_shaders WILDCARD)
    file(GLOB files "${SHADER_ASSETS_DIR}/${WILDCARD}")
    foreach (file ${files})
        get_filename_component(FILENAME ${file} NAME)
        compile_shader(${FILENAME})
    endforeach ()
endfunction()

compile_shaders(*.vert)
compile_shaders(*.frag)